name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: 'npm install'
      - name: Build site
        env:
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          REACT_APP_BASENAME: ${{ secrets.REACT_APP_BASENAME }}
          REACT_APP_CRYPTO_COMPARE_API_KEY: ${{ secrets.REACT_APP_CRYPTO_COMPARE_API_KEY }}
          REACT_APP_FEE_RELAYER_URL: ${{ secrets.REACT_APP_FEE_RELAYER_URL }}
          REACT_APP_SWAP_HOST_FEE_ADDRESS: ${{ secrets.REACT_APP_SWAP_HOST_FEE_ADDRESS }}
          REACT_APP_FIGMENT_DATAHUB_API_KEY: ${{ secrets.REACT_APP_FIGMENT_DATAHUB_API_KEY }}
        run: 'npm run build'
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root # https://github.com/cloudflare/wrangler-action/issues/12#issuecomment-588226602
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
